sudo: false
os: linux
language: python
python:
- '3.5'
- '3.6'
install:
- pip install -r test_requirements.txt
- pip install tox-travis pylintfileheader
script:
- python -m pylint -j 0 -f parseable neptunecontrib tests
- tox
deploy:
  provider: pypi
  username: __token__
  password:
    secure: OVmgLM5O/eOBknYyarV29MLUUvKzUTWTLaXJVei0uW7aMtQBsz0yJq54IbtZnOf2Pcnzjxfn/3lqcmlMRUBwkm0HVxrFRMko1EgfllK293oHdQKsNdHw20grCIBGmu6jF0DqGZ+Tv/QnQU9MTWt9I2y2s6780DVhVSilhBGXWYgF6/FRerdYXpGrNXf6vtIwsaOSBVkFHeojsvlpwO6fO9S8z7O1vv9xunh4R54cBr+QmRGDiVhLllGsGvcfDvWIJx23CjI2/0HcN8Qfh3H7A84ghKMchykJVpxmHThB1kmHYza3BSOPpOaFFfAxAu28vfbH9ZTreEt0CZWq4RgfzaclEe9tp6gGE1q36oHt+CUEt5zX0IPdM+ENCiApLD4qw+W+rYA5TA9dOzmtamlha+DOaUocj+QLULGAqNH12GDRfHwv9jYJhMSCCHu31JcHPBwl6nav/TOjSeIsXn8oXF4BW1eFIv00lxj/4b2doC7nfbQWK2zIw6AL5OSjGyPot/RvV818kaySceEMAzRd3BiRcPGMCciVYG5oj5eGs5RSVydOGh2xLRLJJEmi7k/JWUN4l/UjD590w1mfzAZ14X3fLRLnwaRh+tLuo6YHndAk2g/yOS9UL9pZNivb9asKEiezvUETGATX2zYUYjnjXM4DsjN9MUfwcQUJnmtO6Is=
  on:
    tags: true
  skip_existing: true
