sudo: false
os: linux
language: python
python:
- '3.5.6'
- '3.6'
install:
  - pip install -q -r test_requirements.txt
  - pip install tox-travis pylintfileheader
script:
- python -m pylint -j 0 -f parseable neptunecontrib tests
- tox
deploy:
  provider: pypi
  username: __token__
  distributions: git_version sdist
  password:
    secure: 
  on:
    tags: true
  skip_existing: true
