sudo: false
language: python
python:
- '3.6'
install:
- pip install -r -q requirements.txt
- pip install -r -q test_requirements.txt
- pip install tox-travis pylintfileheader
script:
- python -m pylint -j 0 -f parseable neptunecontrib tests
- tox
deploy:
  distributions: git_version sdist
  provider: pypi
  user: neptune-contrib
  password:
    secure: 47gkGApBZ8Ceq67
on:
  tags: true
skip_existing: true
